### ISSUE TITLE
关于论文的一些疑问

### ISSUE THREAD

**Issue by ZHAIXINGZHAIYUE** [tiandunx/FFC#1]
您好，我有几个疑问需要请教，期待您的回复：
1. 论文中吞吐量的计算，包含了送入g net中的图像吗？
2. 论文中显存占用的对比，是在相同batchsize下吗？该batchsize是否包括送入g net中的数据？
3. 收敛速度和PFC相比如何？我很好奇在训练初期收敛情况是怎么样的？

**Comment by anoymous-face** [comment]
@ZHAIXINGZHAIYUE 1、吞吐量计算时，是网络一次迭代消耗的输入样本。
2、是的
3、收敛速度没有和PFC比较过，训练loss都是很快下降，但是ID小的时候，训练速度确实比不上PFC。

**Comment by tiandunx** [comment]
@ZHAIXINGZHAIYUE 
1、吞吐量的计算是整个网络一次性输入的图片数量，包括g_net
2、是的
3、收敛速度没有和PFC对比过，但是loss都是很快下降，实际训练速度在ID较少的时候确实比不过PFC，因为毕竟有两个网络。

**Comment by ZHAIXINGZHAIYUE** [comment]
您好，能否分享一下训练日志？
